status Table_Underlay(Table *a, Table *b);
status Table_Overlay(Table *a, Table *b);
status Table_Lay(Span *dest, Span *src, boolean overlay);
status Table_Merge(Table *dest, Table *src);
Table *Table_GetOrMake(Table *tbl, void *key, word op);
Span *Table_Ordered(MemCh *m, Table *tbl);
Span *Table_OrdValues(MemCh *m, Table *tbl);
Table *Table_GetOrMake(Table *tbl, void *key, word op);
void *Table_ByPath(Table *tbl, StrVec *path, void *value, word op);
i32 Table_SetByCstr(Table *tbl, char *cstr, void *value);
status Table_SetInTable(Table *orig, void *tblKey, void *key, void *value);
Table *Table_FromSpan(MemCh *m, Span *p);
