Str *Str_ToSha256(MemCh *m, Str *s);
Str *StrVec_ToSha256(MemCh *m, StrVec *v);
Str *StrVec_SaltedDigest(MemCh *m, StrVec *v, Str *salt);
status SignPair_Make(MemCh *m, Str *public, Str *secret, StrVec *phrase);
StrVec *SignPair_Sign(MemCh *m, Str *secret, StrVec *content);
status SignPair_Verify(MemCh *m, Str *public, StrVec *content);
status BoxPair_Make(MemCh *m, Str *public, Str *secret, StrVec *phrase);
status BoxPair_Enc(MemCh *m, Str *secret, StrVec *content);
status BoxPair_Dec(MemCh *m, Str *public, StrVec *content);
status Str_HmacEnc(MemCh *m, Str *s, Str *hmac);
status Str_HmacDec(MemCh *m, Str *s, Str *hmac);
