enum buildeka_types {
    _TYPE_BUILDEKA_START = _NEXT_RANGE_START,
    TYPE_BUILDCTX,
    TYPE_BUILD_MODULE,
    TYPE_BUILD_OBJECT,
    _TYPE_BUILDEKA_END
};

#undef _NEXT_RANGE_START
#define _NEXT_RANGE_START _TYPE_BUILDEKA_END
