boolean TextCharFilter(byte *b, i64 length);
status Str_Reset(Str *s);
status Str_Wipe(Str *s);
i64 Str_ToFd(Str *s, int fd);
i64 Str_Add(Str *s, byte *b, i64 length);
i64 Str_AddCstr(Str *s, char *cstr);
char *Str_Cstr(MemCh *m, Str *s);
Str *Str_Clone(MemCh *m, Str *s, word alloc);
Str *Str_From(MemCh *m, byte *bytes, word length);
Str *Str_Ref(MemCh *m, byte *bytes, word length, word alloc);
Str *Str_CstrRef(MemCh *m, char *cstr);
status Str_Init(Str *s, byte *bytes, word length, word alloc);
Str *Str_Make(MemCh *m, word alloc);
