#include "../mem/mem_chapter.c"
#include "../mem/mem_ctx.c"
#include "../mem/span.c"
#include "../mem/iter.c"
#include "../mem/mem_debug.c"
#include "../core/ifc.c"
#include "../core/init.c"
#include "../core/equals.c"
#include "../str/str.c"
#include "../str/strvec.c"
#include "../str/strvec_fmt.c"
#include "../str/cursor.c"
#include "../str/str_utils.c"
#include "../str/str_debug.c"
#include "../str/str_equals.c"
#include "../str/str_makers.c"
#include "../termio/ansi_str.c"
#include "../sequence/lookup.c"
#include "../debug/debug.c"
#include "../debug/debug_flags.c"
#include "../debug/debug_typestrings.c"
#include "../debug/debug_stack.c"
#include "../termio/cli_status.c"
#include "../core/error.c"

/* file status */
#include "../persist/file_status.c"
/* dir */
#include "../persist/dir.c"
/* spawn */
#include "../persist/procdets.c"
#include "../persist/subprocess.c"
