Str *Time_ToStr(MemCh *m, struct timespec *ts);
void Time_Now(struct timespec *ts);
void Time_ToSpec(struct timespec *ts, microTime tm);
void Time_FromMillis(i64 millis, struct timespec *ts);
i64 Time_ToMillis(struct timespec ts);
Single *Time_Wrapped(MemCh *m, struct timespec *ts);
Str *Time_Today(MemCh *m);
Str *Time_ToDayStr(MemCh *m, struct timespec *ts);
void Time_Combine(struct timespec *ts, struct timespec *add);
void Time_Delay(struct timespec *ts, struct timespec *remaining);
boolean Time_TimeSpecGreater(struct timespec *a, struct timespec *b);
Time_FromSec(i64 seconds, struct timespec *ts);
i64 Time_ToSec(struct timespec *ts);
