status IoUtils_Init(MemCh *m);
status IoUtil_Exists(Str *path);
status IoUtil_Unlink(Str *path);
status IoUtil_AddSlash(StrVec *path);
Str *IoUtil_GetCwdPath(MemCh *m, Str *path);
Str *IoUtil_GetAbsPath(MemCh *m, Str *path);
boolean IoUtil_CmpUpdated(MemCh *m, Str *a, Str *b);
Str *IoUtil_FnameStr(MemCh *m, StrVec *path);
StrVec *IoUtil_BasePath(MemCh *m, StrVec *path);
status IoUtil_Annotate(MemCh *m, StrVec *path);
StrVec *IoUtil_GetAbsVec(MemCh *m, Str *path);
status IoUtil_RemoveSeps(MemCh *m, StrVec *path);
StrVec *IoUtil_AbsVec(MemCh *m, StrVec *v);
status IoUtil_Add(MemCh *m, StrVec *path, StrVec *v);
StrVec *IoAbsPath(MemCh *m, char *cstr);
StrVec *IoPath(MemCh *m, char *cstr);
StrVec *IoPath_From(MemCh *m, Str *s);
