status IoUtils_Init(MemCh *m);
status IoUtil_Exists(Str *path);
status IoUtil_Unlink(Str *path);
status IoUtil_AddSlash(StrVec *path);
Str *IoUtil_GetCwdPath(MemCh *m, Str *path);
Str *IoUtil_GetAbsPath(MemCh *m, Str *path);
boolean IoUtil_CmpUpdated(MemCh *m, Str *a, Str *b);
Str *IoUtil_FnameStr(MemCh *m, StrVec *path);
StrVec *IoUtil_BasePath(MemCh *m, StrVec *path);
status IoUtil_Annotate(MemCh *m, StrVec *path);
StrVec *IoUtil_GetAbsVec(MemCh *m, Str *path);
status IoUtil_RemoveSeps(MemCh *m, StrVec *path);
StrVec *IoUtil_AbsVec(MemCh *m, StrVec *v);
status IoUtil_AddVec(MemCh *m, StrVec *path, StrVec *v);
StrVec *IoUtil_GetExt(MemCh *m, StrVec *path);
StrVec *IoAbsPath(MemCh *m, char *cstr);
StrVec *IoPath(MemCh *m, char *cstr);
StrVec *IoPath_From(MemCh *m, Str *s);
Span *IoUtil_AbsCmdArr(MemCh *m, StrVec *v);
StrVec *IoUtil_AbsPathBuilder(MemCh *m, char *args[]);
Str *IoUtil_PathSep(MemCh *m);
status IoUtil_SwapExt(MemCh *m, StrVec *path, Str *ext);
status IoUtil_AddExt(MemCh *m, StrVec *path, Str *ext);
StrVec *IoUtil_GetExt(MemCh *m, StrVec *path);
boolean IoUtil_IsAbs(StrVec *v);
boolean IoUtil_IsStrAbs(Str *s);
i32 IoUtil_BasePathAnchor(StrVec *path);
