StrVec *StrVec_ToHex(MemCh *m, StrVec *v);
StrVec *StrVec_FromHex(MemCh *m, StrVec *v);
Str *Str_ToHex(MemCh *m, Str *s);
Str *Str_FromHex(MemCh *m, Str *s);
status Bytes_FromHex(MemCh *m, Str *s, byte *nb);
Str *Bytes_ToHexStr(MemCh *m, byte *b, i16 length);
status Raw_FromHex(MemCh *m, Str *s, void *b, i64 sz);
Str *Str_FromHexFiltered(MemCh *m, Str *s);
void Bytes_ToHexOntoStr(MemCh *m, byte *b, byte *ptr, Str *s, i16 length);
util Util_FromHex(MemCh *m, Str *s);
