#define TEST_PORT 1200
status Core_Tests(MemCtx *gm);
status String_Tests(MemCtx *gm);
status Serve_Tests(MemCtx *gm);
status Span_Tests(MemCtx *gm);
status SpanInline_Tests(MemCtx *gm);
status Hash_Tests(MemCtx *gm);
status Roebling_Tests(MemCtx *gm);
status Table_Tests(MemCtx *gm);
status Xml_Tests(MemCtx *gm);
status Match_Tests(MemCtx *gm);
status SpanSetup_Tests(MemCtx *gm);
