/* 16mb or  4096x4096 */
#ifndef __ARCH_HEADER_amd64
#define __ARCH_HEADER_amd64
#define PAGE_SIZE 4096
#define PAGE_COUNT 256
#define PAGE_MAX (256-1)
#define CHAPTER_SIZE PAGE_SIZE*PAGE_COUNT
#define CHAPTER_MAX 16
#define SPAN_MAX_DIMS 5 /* 1,048,576 total items @ 16 slots */
#define SPAN_STRIDE 16
#define SPAN_LOCAL_MAX (SPAN_STRIDE-1)
#define TABLE_MAX_DIMS SPAN_MAX_DIMS
#define STR_MAX 2048
#define STR_DEFAULT 512
#define STR_DEFAULT_MAX STR_DEFAULT-1
#define READ_MAX STR_DEFAULT
#define WRITE_MAX STR_DEFAULT
#endif
