status Path_RangeOf(MemCh *m, StrVec *path, word sep, Coord *cr);
status Path_Around(MemCh *m, StrVec *path, word sep, Coord *cr);
StrVec *Path_Make(MemCh *m, Str *s, Span *sep);
status Path_Annotate(MemCh *m, StrVec *v, Span *sep);
StrVec *Path_Base(MemCh *m, StrVec *path);
Str *Path_StrAdd(MemCh *m, StrVec *path, Str *seg);
status PathStr_StrAdd(Str *s, Str *seg);
status Path_AddSlash(MemCh *m, StrVec *path);
StrVec *Path_Name(MemCh *m, StrVec *path);
StrVec *Path_Ext(MemCh *m, StrVec *path);
boolean Path_ExtEquals(StrVec *path, Str *ext);
status Path_Add(MemCh *m, StrVec *path, StrVec *add);
status Path_SubClone(MemCh *m, StrVec *path, i32 count);
